services:
  postgres:
    image: postgres:16
    container_name: catalog-postgres
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5534:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: